services:
  # 1. O nosso Gerenciador de Estado (Redis)
  redis:
    image: redis:alpine
    container_name: redis_riot
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 2. O Coordenador do Kafka (Zookeeper)
  # O Kafka tradicional precisa do Zookeeper para gerenciar os nós e os tópicos
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_riot
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # 3. A nossa Esteira de Eventos (Apache Kafka)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_riot
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Aqui dizemos pro Kafka liberar a porta 9092 para o seu script Python local
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped