services:
  # 1. O nosso Gerenciador de Estado (Redis)
  redis:
    image: redis:alpine
    container_name: redis_riot
    ports:
      - "6379:6379"
    restart: unless-stopped


  # 2. O Coordenador do Kafka (Zookeeper)
  # O Kafka tradicional precisa do Zookeeper para gerenciar os nós e os tópicos
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper_riot
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # 3. A nossa Esteira de Eventos (Apache Kafka)
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka_riot
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # A MÁGICA ENTRA AQUI NESTAS 3 LINHAS:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  postgres-db: # Nome do serviço (importante para o Consumer!)
    image: postgres:16
    container_name: postgres_pipeline
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3695
      POSTGRES_DB: lol_data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: